### ISSUE TITLE
Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by DeveloperMobilePersonal** [AndersonSMed/axios-queue-js#3]
I don't have much knowledge about node js so when I integrate I'm getting this error and don't know how to fix it. Please help me, thanks!

**Comment by AndersonSMed** [comment]
Hi, could you update the library to the latest version (1.0.5) and see if the problem still occurs?

**Comment by AndersonSMed** [comment]
As I didn't receive any feedback on this thread, I'll be closing this issue. But feel free to open another one if it's needed.
