### ISSUE TITLE
empty dir of package

### ISSUE THREAD

**Issue by sapronov-eugene** [AndersonSMed/axios-queue-js#4]
Hi,

I try to install this package, but I always get an empty package directory.
Maybe you know what could be the problem?

![image](https://user-images.githubusercontent.com/13012071/205492918-41c671e9-6ff5-43ac-a4d5-5cffdbc99eb1.png)

Best Regards

**Comment by AndersonSMed** [comment]
Hello, thanks for this feedback, I fixed this issue in the latest version (1.0.5). Could you try upgrade the package and use it to see if it works as expected?

**Comment by sapronov-eugene** [comment]
Hello, 
Now it's perfect ;)
Thanks a lot.
