### ISSUE TITLE
NPM repo is mostly empty

### ISSUE THREAD

**Issue by webdo** [AndersonSMed/axios-queue-js#5]
Hi, this project is exactly what i have been looking for, but i cannot seem to get the dist folder at all.

As mentionned by someone else in issue #4, installing with NPM/YARN will result in a mostly empty folder as you can see on this picture:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/470782/210009702-e5026f32-d164-41c5-b638-be8118093d1b.png">
You can see it for yourself there: https://www.npmjs.com/package/axios-queue-js?activeTab=explore

I built the repo successfully after adding axios as a dependency.

Thank you!

**Comment by AndersonSMed** [comment]
Hello, thanks for this feedback, I fixed this issue in the latest version (1.0.5). Could you try upgrade the package and use it to see if it works as expected?

**Comment by AndersonSMed** [comment]
First of all, thanks for this feedback. As you already mentioned, this issue duplicates the #4, so I'll be closing this one and will be commenting in the other one to centralize the communication.
